# Generated by Django 5.1 on 2024-08-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_football_footwear_gloves_kits_pump_shinguards_socks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='football',
            name='image',
            field=models.ImageField(null=True, upload_to='./images/football'),
        ),
        migrations.AddField(
            model_name='footwear',
            name='image',
            field=models.ImageField(null=True, upload_to='./images/footwear'),
        ),
        migrations.AddField(
            model_name='gloves',
            name='image',
            field=models.ImageField(null=True, upload_to='./images/gloves'),
        ),
        migrations.AddField(
            model_name='kits',
            name='image',
            field=models.ImageField(null=True, upload_to='./images/kits'),
        ),
        migrations.AddField(
            model_name='pump',
            name='image',
            field=models.ImageField(null=True, upload_to='./images/pump'),
        ),
        migrations.AddField(
            model_name='shinguards',
            name='image',
            field=models.ImageField(null=True, upload_to='./images/shinguards'),
        ),
        migrations.AddField(
            model_name='socks',
            name='image',
            field=models.ImageField(null=True, upload_to='./images/socks'),
        ),
        migrations.AlterField(
            model_name='footwear',
            name='size',
            field=models.IntegerField(),
        ),
    ]
