# Generated by Django 5.1 on 2024-09-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_football_image_footwear_image_gloves_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kits',
            name='size',
            field=models.CharField(max_length=3),
        ),
    ]
