# Generated by Django 5.1 on 2024-09-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_pump_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pump',
            name='size',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.CharField(default='L', max_length=1),
        ),
    ]
