# Generated by Django 5.1 on 2024-09-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_remove_pump_size_cartitem_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='size',
            field=models.CharField(max_length=3),
        ),
    ]
